"""create all table

Revision ID: 90d5416c0bcd
Revises: 
Create Date: 2025-08-01 15:59:08.612950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d5416c0bcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Table: staff
    op.create_table('staff',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('role', sa.Enum('admin', 'staff', name='role'), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('password', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )

    # Table: users
    op.create_table('users',
        sa.Column('id', sa.CHAR(length=36), nullable=False),
        sa.Column('authgear_id', sa.CHAR(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('authgear_id'),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )

    # Table: products
    op.create_table('products',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('product_id', sa.String(length=100), nullable=False),
        sa.Column('product_name', sa.String(length=100), nullable=False),
        sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('product_id'),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )

    # Table: default_life_moments_post_types
    op.create_table('default_life_moments_post_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('type_code', sa.String(length=255), nullable=False),
        sa.Column('zh_hk_type_name', sa.String(length=255), nullable=False),
        sa.Column('zh_hans_type_name', sa.String(length=255), nullable=False),
        sa.Column('en_type_name', sa.String(length=255), nullable=False),
        sa.Column('zh_hk_type_description', sa.String(length=255), nullable=False),
        sa.Column('zh_hans_type_description', sa.String(length=255), nullable=False),
        sa.Column('en_type_description', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('type_code'),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )

    # Table: default_life_trajectory_post_types
    op.create_table('default_life_trajectory_post_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('type_code', sa.String(length=255), nullable=False),
        sa.Column('zh_hk_type_name', sa.String(length=255), nullable=False),
        sa.Column('zh_hans_type_name', sa.String(length=255), nullable=False),
        sa.Column('zh_hk_type_description', sa.String(length=255), nullable=False),
        sa.Column('zh_hans_type_description', sa.String(length=255), nullable=False),
        sa.Column('en_type_name', sa.String(length=255), nullable=False),
        sa.Column('en_type_description', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('type_code'),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )

    # Table: default_message_to_you_post_types
    op.create_table('default_message_to_you_post_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('type_code', sa.String(length=255), nullable=False),
        sa.Column('zh_hk_type_name', sa.String(length=255), nullable=False),
        sa.Column('zh_hans_type_name', sa.String(length=255), nullable=False),
        sa.Column('zh_hk_type_description', sa.String(length=255), nullable=False),
        sa.Column('zh_hans_type_description', sa.String(length=255), nullable=False),
        sa.Column('en_type_name', sa.String(length=255), nullable=False),
        sa.Column('en_type_description', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('type_code'),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )

    # Table: posts_master
    op.create_table('posts_master',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('content', sa.Text(length=16777215), nullable=False),
        sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
        sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
        sa.Column('motion_rate', sa.DECIMAL(precision=10, scale=0), nullable=True),
        sa.Column('images_name', sa.JSON(), nullable=True),
        sa.Column('videos_name', sa.JSON(), nullable=True),
        sa.Column('voices_name', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )

    # Table: post_permissions_groups
    op.create_table('post_permissions_groups',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('group_name', sa.String(length=255), nullable=False),
        sa.Column('create_by', sa.CHAR(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['create_by'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )

    # Table: user_settings
    op.create_table('user_settings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('notification_enabled', sa.Boolean(), server_default='0', nullable=True),
        sa.Column('language', sa.Enum('en', 'zh_hans', 'zh_hk', name='language'), nullable=False),
        sa.Column('maximum_number_inheritor', sa.Integer(), server_default='5', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )
    op.create_index('user_id', 'user_settings', ['user_id'], unique=False)

    # Table: secret_base
    op.create_table('secret_base',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('asset_type', sa.Enum('BANK_ACCOUNT', 'PROPERTY', 'SAFETY_DEPOSIT_BOX', 'CONFIDENTIAL_EVENT', name='asset_type'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('product_id', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )
    op.create_index('product_id', 'secret_base', ['product_id'], unique=False)
    op.create_index('user_id', 'secret_base', ['user_id'], unique=False)

    # Table: custom_life_moments_post_types
    op.create_table('custom_life_moments_post_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('type_name', sa.String(length=255), nullable=False),
        sa.Column('type_description', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )
    op.create_index('user_id', 'custom_life_moments_post_types', ['user_id'], unique=False)

    # Table: custom_life_trajectory_post_types
    op.create_table('custom_life_trajectory_post_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('type_name', sa.String(length=255), nullable=False),
        sa.Column('type_description', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )
    op.create_index('user_id', 'custom_life_trajectory_post_types', ['user_id'], unique=False)

    # Table: transaction
    op.create_table('transaction',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('payment_service_provider', sa.Enum('APPLE', 'GOOGLE', name='payment_service_provider'), nullable=False),
        sa.Column('payment_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='payment_status'), nullable=False),
        sa.Column('payment_type', sa.Enum('CONSUMPTION', 'SUBSCRIPTION', name='payment_type'), nullable=False),
        sa.Column('transaction_id', sa.String(length=100), nullable=True),
        sa.Column('purchase_date', sa.DateTime(), nullable=True),
        sa.Column('purchase_token', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('product_id', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('product_id', 'transaction', ['product_id'], unique=False)
    op.create_index('user_id', 'transaction', ['user_id'], unique=False)

    # Table: post_user_permissions
    op.create_table('post_user_permissions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('shared_post_id', sa.Integer(), nullable=False),
        sa.Column('shared_by', sa.CHAR(length=36), nullable=False),
        sa.Column('post_source', sa.Enum('LIFE_MOMENT', 'MESSAGE_TO_YOU', 'LIFE_TRAJECTORY', name='post_source'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )
    op.create_index('shared_by', 'post_user_permissions', ['shared_by'], unique=False)

    # Table: bank_account
    op.create_table('bank_account',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('bank_account_name', sa.Text(), nullable=False),
        sa.Column('bank_account_number', sa.Text(), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('meta_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['meta_id'], ['secret_base.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('meta_id', 'bank_account', ['meta_id'], unique=False)

    # Table: property
    op.create_table('property',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('property_name', sa.Text(), nullable=False),
        sa.Column('property_address', sa.Text(), nullable=False),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('meta_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['meta_id'], ['secret_base.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('meta_id', 'property', ['meta_id'], unique=False)

    # Table: safety_deposit_box
    op.create_table('safety_deposit_box',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('safety_deposit_box_name', sa.Text(), nullable=False),
        sa.Column('safety_deposit_box_open_method', sa.Text(), nullable=False),
        sa.Column('safety_deposit_box_address', sa.Text(), nullable=False),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('meta_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['meta_id'], ['secret_base.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('meta_id', 'safety_deposit_box', ['meta_id'], unique=False)

    # Table: confidential_event
    op.create_table('confidential_event',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('event_name', sa.Text(), nullable=False),
        sa.Column('event_details', sa.Text(), nullable=False),
        sa.Column('meta_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['meta_id'], ['secret_base.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('meta_id', 'confidential_event', ['meta_id'], unique=False)

    # Table: goods_donor
    op.create_table('goods_donor',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('image_url_1', sa.Text(), nullable=True),
        sa.Column('image_url_2', sa.Text(), nullable=True),
        sa.Column('image_url_3', sa.Text(), nullable=True),
        sa.Column('goods_info', sa.Text(), nullable=False),
        sa.Column('donor_organization', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'goods_donor', ['user_id'], unique=False)

    # Table: user_beneficiaries
    op.create_table('user_beneficiaries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('beneficiary_type', sa.Enum('PHONE', 'INSURANCE', name='beneficiary_type'), nullable=False),
        sa.Column('platform_or_company', sa.Text(), nullable=False),
        sa.Column('first_name', sa.Text(), nullable=False),
        sa.Column('last_name', sa.Text(), nullable=False),
        sa.Column('relation', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'user_beneficiaries', ['user_id'], unique=False)

    # Table: user_inheritor
    op.create_table('user_inheritor',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('inviate_status', sa.Enum('WIP', 'ACCEPT', 'REJECT', 'EXPIRE', name='inviate_status'), nullable=False),
        sa.Column('invitation_expire_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('phone_number', sa.String(length=100), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('inheritor_user_id', sa.CHAR(length=36), nullable=True),
        sa.Column('first_name', sa.String(length=50), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column('jwt', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['inheritor_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('inheritor_user_id', 'user_inheritor', ['inheritor_user_id'], unique=False)
    op.create_index('user_id', 'user_inheritor', ['user_id'], unique=False)

    # Table: posts_permissions_group_members
    op.create_table('posts_permissions_group_members',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('phone_number_prefix', sa.Integer(), nullable=False),
        sa.Column('phone_number', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=255), nullable=False),
        sa.Column('last_name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['group_id'], ['post_permissions_groups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )
    op.create_index('group_id', 'posts_permissions_group_members', ['group_id'], unique=False)
    op.create_index('user_id', 'posts_permissions_group_members', ['user_id'], unique=False)

    # Table: user_beneficiaries_meta
    op.create_table('user_beneficiaries_meta',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('contact_country_code', sa.String(length=100), nullable=False),
        sa.Column('contact_number', sa.String(length=100), nullable=False),
        sa.Column('meta_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['meta_id'], ['user_beneficiaries.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('meta_id', 'user_beneficiaries_meta', ['meta_id'], unique=False)

    # Table: user_inheritor_meta
    op.create_table('user_inheritor_meta',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('LB', sa.Boolean(), server_default='0', nullable=True, comment='Love Bequeathed'),
        sa.Column('OP', sa.Boolean(), server_default='0', nullable=True, comment='Obituaries'),
        sa.Column('LET', sa.Boolean(), server_default='0', nullable=True, comment='Life Events Timeline'),
        sa.Column('SB', sa.Boolean(), server_default='0', nullable=True, comment='Secret Base'),
        sa.Column('HM', sa.Boolean(), server_default='0', nullable=True, comment='Health Management'),
        sa.Column('MTS', sa.Boolean(), server_default='0', nullable=True, comment='Message To Someone'),
        sa.Column('LS', sa.Boolean(), server_default='0', nullable=True, comment='Legal Summiries'),
        sa.Column('FC', sa.Boolean(), server_default='0', nullable=True, comment='Financial Chapter'),
        sa.Column('PE', sa.Boolean(), server_default='0', nullable=True, comment='Personal Effects'),
        sa.Column('meta_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['meta_id'], ['user_inheritor.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('meta_id', 'user_inheritor_meta', ['meta_id'], unique=False)

    # Table: post_shared_recipients
    op.create_table('post_shared_recipients',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('permission_id', sa.Integer(), nullable=False),
        sa.Column('shared_to', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['permission_id'], ['post_user_permissions.id'], ),
        sa.ForeignKeyConstraint(['shared_to'], ['posts_permissions_group_members.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )
    op.create_index('permission_id', 'post_shared_recipients', ['permission_id'], unique=False)
    op.create_index('shared_to', 'post_shared_recipients', ['shared_to'], unique=False)

    # Table: life_moments
    op.create_table('life_moments',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('post_master_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('weather', sa.String(length=255), nullable=True),
        sa.Column('participants', sa.String(length=255), nullable=True),
        sa.Column('post_type_code', sa.String(length=255), nullable=True),
        sa.Column('custom_post_type_id', sa.Integer(), nullable=True),
        sa.Column('restaurant_name', sa.String(length=255), nullable=True),
        sa.Column('food_name', sa.String(length=255), nullable=True),
        sa.Column('academic_work_interest', sa.String(length=255), nullable=True),
        sa.Column('school_score', sa.String(length=20), nullable=True),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['custom_post_type_id'], ['custom_life_moments_post_types.id'], ),
        sa.ForeignKeyConstraint(['post_master_id'], ['posts_master.id'], ),
        sa.ForeignKeyConstraint(['post_type_code'], ['default_life_moments_post_types.type_code'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('custom_post_type_id', 'life_moments', ['custom_post_type_id'], unique=False)
    op.create_index('post_master_id', 'life_moments', ['post_master_id'], unique=False)
    op.create_index('post_type_code', 'life_moments', ['post_type_code'], unique=False)
    op.create_index('user_id', 'life_moments', ['user_id'], unique=False)

    # Table: life_trajectories
    op.create_table('life_trajectories',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('post_master_id', sa.Integer(), nullable=False),
        sa.Column('post_type_code', sa.String(length=255), nullable=True),
        sa.Column('custom_post_type_id', sa.Integer(), nullable=True),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['custom_post_type_id'], ['custom_life_trajectory_post_types.id'], ),
        sa.ForeignKeyConstraint(['post_master_id'], ['posts_master.id'], ),
        sa.ForeignKeyConstraint(['post_type_code'], ['default_life_trajectory_post_types.type_code'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('custom_post_type_id', 'life_trajectories', ['custom_post_type_id'], unique=False)
    op.create_index('post_master_id', 'life_trajectories', ['post_master_id'], unique=False)
    op.create_index('post_type_code', 'life_trajectories', ['post_type_code'], unique=False)
    op.create_index('user_id', 'life_trajectories', ['user_id'], unique=False)

    # Table: love_left_in_the_world
    op.create_table('love_left_in_the_world',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'love_left_in_the_world', ['user_id'], unique=False)

    # Table: message_to_you
    op.create_table('message_to_you',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.Column('post_master_id', sa.Integer(), nullable=False),
        sa.Column('post_type_code', sa.String(length=255), nullable=False),
        sa.Column('when_can_read_the_post', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['post_master_id'], ['posts_master.id'], ),
        sa.ForeignKeyConstraint(['post_type_code'], ['default_message_to_you_post_types.type_code'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('post_master_id', 'message_to_you', ['post_master_id'], unique=False)
    op.create_index('post_type_code', 'message_to_you', ['post_type_code'], unique=False)
    op.create_index('user_id', 'message_to_you', ['user_id'], unique=False)

    # Table: organs_donor
    op.create_table('organs_donor',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('did_arrange_organ_donor', sa.Enum('YES', 'NO', 'NOT_YET', name='did_arrange_organ_donor'), server_default='NOT_YET', nullable=True),
        sa.Column('contact_organization', sa.Text(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'organs_donor', ['user_id'], unique=False)

    # Table: pass_away_info
    op.create_table('pass_away_info',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('death_time', sa.DateTime(), nullable=False),
        sa.Column('death_certificate', sa.Text(), nullable=True),
        sa.Column('id_card_copy', sa.Text(), nullable=True),
        sa.Column('relationship_proof', sa.Text(), nullable=True),
        sa.Column('inheritor_id_proof', sa.Text(), nullable=True),
        sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('meta_id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['meta_id'], ['user_inheritor.id'], ),
        sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('meta_id', 'pass_away_info', ['meta_id'], unique=False)
    op.create_index('transaction_id', 'pass_away_info', ['transaction_id'], unique=False)

    # Table: subscription_meta
    op.create_table('subscription_meta',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('subscription_expire_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('meta_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['meta_id'], ['transaction.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4'
    )
    op.create_index('meta_id', 'subscription_meta', ['meta_id'], unique=False)

    # Table: user_testament
    op.create_table('user_testament',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('did_testament', sa.Boolean(), server_default='0', nullable=True),
        sa.Column('did_testament_date', sa.DateTime(), nullable=True),
        sa.Column('testament_store_in', sa.Text(), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'user_testament', ['user_id'], unique=False)

    # Table: push_notification
    op.create_table('push_notification',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('token', sa.String(length=100), nullable=True),
        sa.Column('device_uuid', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'push_notification', ['user_id'], unique=False)

    # Table: palliative_care
    op.create_table('palliative_care',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('did_arrange', sa.Enum('AGREE', 'NOT_AGREE', 'NOT_YET', name='did_arrange_palliative'), server_default='NOT_YET', nullable=True),
        sa.Column('contact_organization', sa.String(length=255), nullable=False),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'palliative_care', ['user_id'], unique=False)

    # Table: medical_preference
    op.create_table('medical_preference',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('did_arrange', sa.Enum('DID', 'NOT_DID', 'NOT_YET', name='did_arrange_medical'), server_default='NOT_YET', nullable=True),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'medical_preference', ['user_id'], unique=False)

    # Table: enduring_power_of_attorney
    op.create_table('enduring_power_of_attorney',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('did_arrange', sa.Enum('DID', 'NOT_DID', 'NOT_YET', name='did_arrange_attorney'), server_default='NOT_YET', nullable=True),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'enduring_power_of_attorney', ['user_id'], unique=False)

    # Table: ceremony_preference
    op.create_table('ceremony_preference',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('did_arrange', sa.Enum('BUDDHISM', 'TAOISM', 'CHRISTIANITY', 'NOT_YET', 'CUSTOM', name='did_arrange_ceremony'), server_default='NOT_YET', nullable=True),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('custom', sa.String(length=100), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'ceremony_preference', ['user_id'], unique=False)

    # Table: coffin
    op.create_table('coffin',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('did_arrange', sa.Enum('CHINESE', 'WEST', 'EF', 'NOT_YET', 'CUSTOM', name='did_arrange_coffin'), server_default='NOT_YET', nullable=True),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('custom', sa.String(length=100), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'coffin', ['user_id'], unique=False)

    # Table: funeral
    op.create_table('funeral',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('did_arrange', sa.Enum('CREMATION', 'BURIAL', 'NOT_YET', 'CUSTOM', name='did_arrange_funeral'), server_default='NOT_YET', nullable=True),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('custom', sa.String(length=100), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'funeral', ['user_id'], unique=False)

    # Table: ashes
    op.create_table('ashes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('did_arrange', sa.Enum('CB', 'SAITGOR', 'SAOTS', 'CR', 'NOT_YET', 'CUSTOM', name='did_arrange_ashes'), server_default='NOT_YET', nullable=True),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('custom', sa.String(length=100), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'ashes', ['user_id'], unique=False)

    # Table: describe_yourself_ten_sentences
    op.create_table('describe_yourself_ten_sentences',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('content', sa.String(length=1000), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'describe_yourself_ten_sentences', ['user_id'], unique=False)

    # Table: value_of_life
    op.create_table('value_of_life',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('content', sa.String(length=1000), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'value_of_life', ['user_id'], unique=False)

    # Table: life_insights
    op.create_table('life_insights',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('content', sa.String(length=1000), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'life_insights', ['user_id'], unique=False)

    # Table: epitaph
    op.create_table('epitaph',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('content', sa.String(length=1000), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'epitaph', ['user_id'], unique=False)

    # Table: favorite_headshot
    op.create_table('favorite_headshot',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('picture', sa.String(length=200), nullable=True),
        sa.Column('ago', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('user_id', sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('user_id', 'favorite_headshot', ['user_id'], unique=False)

    # Table: pass_away_info_meta
    op.create_table('pass_away_info_meta',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('approval_status', sa.Enum('VERIFY', 'APPROVAL', 'REJECT', name='approval_status'), nullable=False),
        sa.Column('approval_comments', sa.String(length=500), nullable=True),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column('admin_user_id', sa.Integer(), nullable=True),
        sa.Column('meta_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['admin_user_id'], ['staff.id'], ),
        sa.ForeignKeyConstraint(['meta_id'], ['pass_away_info.id'], ),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_encryption='Y'
    )
    op.create_index('admin_user_id', 'pass_away_info_meta', ['admin_user_id'], unique=False)
    op.create_index('meta_id', 'pass_away_info_meta', ['meta_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in reverse order to handle foreign key dependencies
    op.drop_table('pass_away_info_meta')
    op.drop_table('favorite_headshot')
    op.drop_table('epitaph')
    op.drop_table('life_insights')
    op.drop_table('value_of_life')
    op.drop_table('describe_yourself_ten_sentences')
    op.drop_table('ashes')
    op.drop_table('funeral')
    op.drop_table('coffin')
    op.drop_table('ceremony_preference')
    op.drop_table('enduring_power_of_attorney')
    op.drop_table('medical_preference')
    op.drop_table('palliative_care')
    op.drop_table('push_notification')
    op.drop_table('user_testament')
    op.drop_table('subscription_meta')
    op.drop_table('pass_away_info')
    op.drop_table('organs_donor')
    op.drop_table('message_to_you')
    op.drop_table('love_left_in_the_world')
    op.drop_table('life_trajectories')
    op.drop_table('life_moments')
    op.drop_table('post_shared_recipients')
    op.drop_table('user_inheritor_meta')
    op.drop_table('user_beneficiaries_meta')
    op.drop_table('posts_permissions_group_members')
    op.drop_table('user_inheritor')
    op.drop_table('user_beneficiaries')
    op.drop_table('goods_donor')
    op.drop_table('confidential_event')
    op.drop_table('safety_deposit_box')
    op.drop_table('property')
    op.drop_table('bank_account')
    op.drop_table('post_user_permissions')
    op.drop_table('transaction')
    op.drop_table('custom_life_trajectory_post_types')
    op.drop_table('custom_life_moments_post_types')
    op.drop_table('secret_base')
    op.drop_table('user_settings')
    op.drop_table('post_permissions_groups')
    op.drop_table('posts_master')
    op.drop_table('default_message_to_you_post_types')
    op.drop_table('default_life_trajectory_post_types')
    op.drop_table('default_life_moments_post_types')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('staff')

    # ### end Alembic commands ###