import os
from dotenv import load_dotenv
load_dotenv()

env = os.getenv('ENV', 'local') 

if env == 'staging':
    load_dotenv('.env.staging')
if env == 'production':
    load_dotenv('.env.production')
if env == 'local.Docker':
    load_dotenv('.env.local.docker')    
else:
    load_dotenv('.env')
    

ENV = env

DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')

AUTHGEAR_ENDPOINT = os.getenv('AUTHGEAR_ENDPOINT')
AUTHGEAR_ADMIN_API_KEY_PATH = os.getenv('AUTHGEAR_ADMIN_API_KEY_PATH')
AUTHGEAR_ADMIN_API_ENDPOINT = os.getenv('AUTHGEAR_ADMIN_API_ENDPOINT')
AUTHGEAR_PROJECT_ID = os.getenv('AUTHGEAR_PROJECT_ID')
AUTHGEAR_KEY_ID = os.getenv('AUTHGEAR_KEY_ID')

AUTHGEAR_ADMIN_PORTAL_ENDPOINT=os.getenv('AUTHGEAR_ADMIN_PORTAL_ENDPOINT')
AUTHGEAR_ADMIN_PORTAL_ADMIN_API_ENDPOINT=os.getenv('AUTHGEAR_ADMIN_PORTAL_ADMIN_API_ENDPOINT')
AUTHGEAR_ADMIN_PORTAL_ADMIN_API_KEY_PATH=os.getenv('AUTHGEAR_ADMIN_PORTAL_ADMIN_API_KEY_PATH')
AUTHGEAR_ADMIN_PORTAL_PROJECT_ID=os.getenv('AUTHGEAR_ADMIN_PORTAL_PROJECT_ID')
AUTHGEAR_ADMIN_PORTAL_KEY_ID=os.getenv('AUTHGEAR_ADMIN_PORTAL_KEY_ID')



ALICLOUD_OSS_ENDPOINT = os.getenv('ALICLOUD_OSS_ENDPOINT')
ALICLOUD_OSS_DEEPSOUL_BUCKET_NAME = os.getenv('ALICLOUD_OSS_DEEPSOUL_BUCKET_NAME')
ALICLOUD_OSS_DEEPSOUL_ACCELERATE_REGION_NAME=os.getenv('ALICLOUD_OSS_DEEPSOUL_ACCELERATE_REGION_NAME')
ALICLOUD_OSS_ACCESS_KEY_ID = os.getenv('ALICLOUD_OSS_ACCESS_KEY_ID')
ALICLOUD_OSS_ACCESS_KEY_SECRET = os.getenv('ALICLOUD_OSS_ACCESS_KEY_SECRET')
ALICLOUD_OSS_REGION = os.getenv('ALICLOUD_OSS_REGION')
ALICLOUD_OSS_REGION_ID = os.getenv('ALICLOUD_OSS_REGION_ID')
ALICLOUD_OSS_STS_ROLE_ARN = os.getenv('ALICLOUD_OSS_STS_ROLE_ARN')



SIGNATURE_SECRET = os.getenv('SIGNATURE_SECRET')

VONAGE_API_KEY=os.getenv('VONAGE_API_KEY')
VONAGE_API_SECRET=os.getenv('VONAGE_API_SECRET')

# APPLE PAYMENT 配置
APPLE_VERIFY_URL=os.getenv('APPLE_VERIFY_URL')
APPLE_SANDBOX_VERIFY_URL=os.getenv('APPLE_SANDBOX_VERIFY_URL')
APPLE_SHARED_SECRET=os.getenv('APPLE_SHARED_SECRET')

# Google PAYMENT 配置
GOOGLE_SERVICE_ACCOUNT_FILE_PATH = os.getenv('GOOGLE_SERVICE_ACCOUNT_FILE_PATH')
GOOGLE_RETURN_SCOPES = os.getenv('GOOGLE_RETURN_SCOPES')
GOOGLE_PACKAGE_NAME = os.getenv('GOOGLE_PACKAGE_NAME')

#DKMS
DKMS_MASTER_CRYPTO_KEY = os.getenv('DKMS_MASTER_CRYPTO_KEY')
DKMS_CLIENT_END_POINT = os.getenv('DKMS_CLIENT_END_POINT')
DKMS_INSTANCE_ID = os.getenv('DKMS_INSTANCE_ID') 
DKMS_CLIENT_KEY_FILE = os.getenv('DKMS_CLIENT_KEY_FILE') 
DKMS_CLIENT_KEY_PASSWORD = os.getenv('DKMS_CLIENT_KEY_PASSWORD')
DKMS_CA_CERT = os.getenv('DKMS_CA_CERT')
DKMS_RDS_SECRET=os.getenv('DKMS_RDS_SECRET')
DKMS_OSS_SECRET=os.getenv('DKMS_OSS_SECRET')

#----- In-app purchase ProductID
IN_APP_PURCHASE_C001=os.getenv('IN_APP_PURCHASE_C001')
IN_APP_PURCHASE_C002=os.getenv('IN_APP_PURCHASE_C002')
IN_APP_PURCHASE_C003=os.getenv('IN_APP_PURCHASE_C003')
IN_APP_PURCHASE_S001=os.getenv('IN_APP_PURCHASE_S001')
IN_APP_PURCHASE_S002=os.getenv('IN_APP_PURCHASE_S002')

IN_APP_PURCHASE_NO_NEED_TO_PAY_CONSUMER=os.getenv('IN_APP_PURCHASE_NO_NEED_TO_PAY_CONSUMER')
IN_APP_PURCHASE_NO_NEED_TO_PAY_SUBSCRIPTION=os.getenv('IN_APP_PURCHASE_NO_NEED_TO_PAY_SUBSCRIPTION')

#----- D7 Network API
D7NETWORK_API_ENDPOINT = os.getenv('D7NETWORK_API_ENDPOINT')
D7NETWORK_API_KEY = os.getenv('D7NETWORK_API_KEY')
D7NETWORK_API_REPORT_ENDPOINT = os.getenv('D7NETWORK_API_REPORT_ENDPOINT')
D7NETWORK_API_ULINK_ENDPOINT = os.getenv('D7NETWORK_API_ULINK_ENDPOINT')

#----- Cloud Messaging API
CLOUD_MESSAGING_API_ENDPOINT = os.getenv('CLOUD_MESSAGING_API_ENDPOINT')

#----- AliGreen API
ALICLOUD_GREEN_ACCESS_KEY_ID = os.getenv('ALICLOUD_GREEN_ACCESS_KEY_ID')
ALICLOUD_GREEN_ACCESS_KEY_SECRET = os.getenv('ALICLOUD_GREEN_ACCESS_KEY_SECRET')
ALICLOUD_GREEN_REGION_ID = os.getenv('ALICLOUD_GREEN_REGION_ID')
ALICLOUD_GREEN_ENDPOINT = os.getenv('ALICLOUD_GREEN_ENDPOINT')

#----- Alibaba Cloud DashScope API
DASHSCOPE_API_KEY = os.getenv('DASHSCOPE_API_KEY')
DASHSCOPE_BASE_URL = os.getenv('DASHSCOPE_BASE_URL')
DKMS_DASHSCOPE_API_KEY_SECRET=os.getenv('DKMS_DASHSCOPE_API_KEY_SECRET')

# SECRET_KEY =  os.getenv('SECRET_KEY')
# ALGORITHM = "HS256"  # Algorithm used for encoding JWT
# ACCESS_TOKEN_EXPIRE_MINUTES = 30  # Token expiration time in minutes

# AWS_ACCESS_KEY_ID = "your_aws_access_key_id"  # AWS access key
# AWS_SECRET_ACCESS_KEY = "your_aws_secret_access_key"  # AWS secret key
# AWS_REGION = "us-east-1"  # AWS region for services

# POSTS_PER_PAGE = 10  # Default number of posts per page for pagination

# Add any other global configuration settings as needed