import enum

# FILE: /my-python-app/my-python-app/src/auth/constants.py

# Status
STATUS_SUCCESS = "SUCCESS"
STATUS_ERRPR = "ERROR"





# Error Code
SUCCESS_CODE_200 = 200
BAD_REQUEST_CODE_400 = 400
UNAUTHORIZED_CODE_401 = 401
FORBIDDEN_CODE_403 = 403
INVALID_REQUEST_DATA_CODE_422 = 422
INTERNAL_SERVER_ERROR_CODE_500 = 500
FILE_SIZE_EXCEEDS_LIMIT_CODE = "FILE_SIZE_EXCEEDS_LIMIT"
INVALID_IMAGE_FILE_CODE = "INVALID_IMAGE_FILE"


#  Transaction operation
TRANSACTION_CUSTOM_OPERATION_REMOVE_ALL_POST_SHARED_TO = "TRANSACTION_CUSTOM_OPERATION_REMOVE_ALL_POST_SHARED_TO"
TRANSACTION_CUSTOM_OPERATION_CREATE_MUTLI_RECIPIENTS = "TRANSACTION_CUSTOM_OPERATION_CREATE_MUTLI_RECIPIENTS"
TRANSACTION_CUSTOM_OPERATION_DELETE_SHARED_TO_MEMBER_IN_GROUP = "TRANSACTION_CUSTOM_OPERATION_DELETE_SHARED_TO_MEMBER_IN_GROUP"
class ORM_OPERATION_TYPE(enum.Enum):
    UPDATE = "update"
    DELETE = "delete"
    INSERT = "insert"
    CUSTOM = "custom"
