# Reply related constants
MAX_REPLY_CONTENT_LENGTH = 1000
MIN_REPLY_CONTENT_LENGTH = 1

# Error messages
ERROR_REPLY_PERMISSION_DENIED = "REPLY_PERMISSION_DENIED"
ERROR_PARENT_REPLY_NOT_FOUND = "PARENT_REPLY_NOT_FOUND"
ERROR_INVALID_REPLY_CONTENT = "INVALID_REPLY_CONTENT"
